services:
  reports:
    build: ./services/report
    ports:
      - "8001:8000"
    env_file:
      - .env

  geolocations:
    build: ./services/geolocation
    ports:
      - "8002:8000"
    env_file:
      - .env

  emails:
    build: ./services/email
    ports:
      - "8003:8000"
    env_file:
      - .env
  coupons:
    build: ./services/coupon
    ports:
      - "8004:8000"
    env_file:
      - .env
