services:
  coupon:
    build:
      context: ./services/coupon  
      dockerfile: Dockerfile
    container_name: coupon_service
    ports:
      - "8001:8000"  
    volumes:
      - ./services/coupon:/app
    environment:
      - PORT=8000
  email:
    build:
      context: ./services/email 
      dockerfile: Dockerfile
    container_name: email_service
    ports:
      - "8002:8000"  
    volumes:
      - ./services/email:/app
    environment:
      - PORT=8000
  geolocation:
    build:
      context: ./services/geolocation 
      dockerfile: Dockerfile
    container_name: geolocation_service
    ports:
      - "8003:8000"  
    volumes:
      - ./services/geolocation:/app
    environment:
      - PORT=8000
  report:
    build:
      context: ./services/report
      dockerfile: Dockerfile
    container_name: report_service
    ports:
      - "8004:8000"  
    volumes:
      - ./services/report:/app
    environment:
      - PORT=8000


