"""
Module for coupon data model and operations.

This module defines the coupon model using Pydantic for data validation
and serialization of coupon information.

Author: Juan Nicolás Diaz Salamanca <jndiaz@udistrital.edu.co>
"""

from pydantic import BaseModel

class Coupon(BaseModel):

    """
    Represents a coupon with its properties and methods for serialization.
    Attributes:
    - code: Unique code for the coupon.
    - id: Unique identifier for the coupon.
    - text: Text description of the coupon.
    - discount: Discount percentage as a float (e.g., 0.2 for 20%).
    - creation_date: Date when the coupon was created.
    - expiration_date: Date when the coupon expires.
    - enabled: Boolean indicating if the coupon is currently enabled.

    Methods:
    - __str__: Returns a string representation of the coupon.
    - __to_dict__: Returns a dictionary representation of the coupon for serialization.
    -__init__: Initializes the coupon code based on the text and id.
    """

    code: str
    id: int
    text: str
    discount: float
    creation_date: str
    expiration_date: str
    enabled: bool

    def __init__(self):
        """
        Initializes the coupon code based on the text and id.
        The code is generated by concatenating the text and id of the coupon.
        For example, if the text is "WELCOME" and the id is 1, the code will be "WELCOME1".
        """
        self.code = self.text + self.id

    def __str__(self):
        """
        Returns a string representation of the coupon.
        The string includes the code, discount, creation date, expiration date, and enabled status.
        For example: "Coupon(code=WELCOME1, discount=0.2, creation_date=2026-01-01, expiration_date=2026-12-31, enabled=True)"
        """
        return f"Coupon(code={self.code}, discount={self.discount},creation_date={self.creation_date}, expiration_date={self.expiration_date}, enabled={self.enabled})"
    
    def __to_dict__(self):
        """
        Returns a dictionary representation of the coupon for serialization.
        The dictionary includes the code, discount, expiration date, and enabled status.
        For example: {"code": "WELCOME1", "discount": 0.2, "expiration_date": "2026-12-31", "enabled": True}
        """
        return {
            "code": self.code,
            "discount": self.discount,
            "expiration_date": self.expiration_date,
            "enabled": self.enabled
        }
    
